### ISSUE TITLE
[elasticsearch] No Living Connections

### ISSUE THREAD

**Issue by elzii** [rekibnikufesin/nodejs-api-swagger#2]
Still can't seem to get elasticsearch running. The Kibana console runs fine at http://localhost:5601/

This is after wiping clean and following your instructions at bottom of README.

Any ideas?

```
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:13:10Z","tags":["warning","elasticsearch","admin"],"pid":12,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:13:10Z","tags":["warning","elasticsearch","admin"],"pid":12,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:22:48Z","tags":["error","elasticsearch","admin"],"pid":12,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 92.242.140.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:23:12Z","tags":["warning","elasticsearch","admin"],"pid":12,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```

**Comment by elzii** [comment]
Is something being set in a `runtime.yaml` that is being ignored from the repo maybe?

**Comment by rekibnikufesin** [comment]
Is that all that is being logged?
Kibana is expected to log that out initially while elasticsearch is starting up. Right after that, elasticsearch should start logging out status updates. If there are additional log messages, post them here and I'll take a look. Mine posted below for reference:
```
Starting nodejsapiswagger_elasticsearch_1
Starting nodejsapiswagger_kibana_1
Attaching to nodejsapiswagger_elasticsearch_1, nodejsapiswagger_kibana_1
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","plugin:kibana@5.0.2","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","plugin:elasticsearch@5.0.2","info"],"pid":11,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","plugin:console@5.0.2","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["error","elasticsearch"],"pid":11,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.21.0.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["warning","elasticsearch"],"pid":11,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","plugin:elasticsearch@5.0.2","error"],"pid":11,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","plugin:timelion@5.0.2","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["listening","info"],"pid":11,"message":"Server running at http://0.0.0.0:5601"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:10Z","tags":["status","ui settings","error"],"pid":11,"state":"red","message":"Status changed from uninitialized to red - Elasticsearch plugin is red","prevState":"uninitialized","prevMsg":"uninitialized"}
elasticsearch_1  | [2017-04-03T19:55:10,532][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2017-04-03T19:55:10,698][INFO ][o.e.e.NodeEnvironment    ] [U95imVd] using [1] data paths, mounts [[/usr/share/elasticsearch/data (osxfs)]], net usable_space [147.9gb], net total_space [464.7gb], spins? [possibly], types [fuse.osxfs]
elasticsearch_1  | [2017-04-03T19:55:10,698][INFO ][o.e.e.NodeEnvironment    ] [U95imVd] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch_1  | [2017-04-03T19:55:10,925][INFO ][o.e.n.Node               ] [U95imVd] node name [U95imVd] derived from node ID; set [node.name] to override
elasticsearch_1  | [2017-04-03T19:55:10,932][INFO ][o.e.n.Node               ] [U95imVd] version[5.0.2], pid[1], build[f6b4951/2016-11-24T10:07:18.101Z], OS[Linux/4.9.12-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111/25.111-b14]
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:12Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:12Z","tags":["warning","elasticsearch"],"pid":11,"message":"No living connections"}
elasticsearch_1  | [2017-04-03T19:55:14,184][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2017-04-03T19:55:14,184][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [ingest-common]
elasticsearch_1  | [2017-04-03T19:55:14,184][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [lang-expression]
elasticsearch_1  | [2017-04-03T19:55:14,184][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [lang-groovy]
elasticsearch_1  | [2017-04-03T19:55:14,185][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [lang-mustache]
elasticsearch_1  | [2017-04-03T19:55:14,185][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [lang-painless]
elasticsearch_1  | [2017-04-03T19:55:14,185][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [percolator]
elasticsearch_1  | [2017-04-03T19:55:14,186][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [reindex]
elasticsearch_1  | [2017-04-03T19:55:14,186][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [transport-netty3]
elasticsearch_1  | [2017-04-03T19:55:14,186][INFO ][o.e.p.PluginsService     ] [U95imVd] loaded module [transport-netty4]
elasticsearch_1  | [2017-04-03T19:55:14,187][INFO ][o.e.p.PluginsService     ] [U95imVd] no plugins loaded
elasticsearch_1  | [2017-04-03T19:55:14,546][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:15Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:15Z","tags":["warning","elasticsearch"],"pid":11,"message":"No living connections"}
elasticsearch_1  | [2017-04-03T19:55:17,208][INFO ][o.e.n.Node               ] [U95imVd] initialized
elasticsearch_1  | [2017-04-03T19:55:17,208][INFO ][o.e.n.Node               ] [U95imVd] starting ...
elasticsearch_1  | [2017-04-03T19:55:17,580][INFO ][o.e.t.TransportService   ] [U95imVd] publish_address {172.21.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2017-04-03T19:55:17,587][INFO ][o.e.b.BootstrapCheck     ] [U95imVd] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:17Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:17Z","tags":["warning","elasticsearch"],"pid":11,"message":"No living connections"}
elasticsearch_1  | [2017-04-03T19:55:18,318][WARN ][o.e.m.j.JvmGcMonitorService] [U95imVd] [gc][1] overhead, spent [552ms] collecting in the last [1s]
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:20Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:20Z","tags":["warning","elasticsearch"],"pid":11,"message":"No living connections"}
elasticsearch_1  | [2017-04-03T19:55:20,714][INFO ][o.e.c.s.ClusterService   ] [U95imVd] new_master {U95imVd}{U95imVd4TU6qeITnnt8p6g}{Ex5YPMkPQr64Ge0pcvV0aA}{172.21.0.2}{172.21.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
elasticsearch_1  | [2017-04-03T19:55:20,746][INFO ][o.e.h.HttpServer         ] [U95imVd] publish_address {172.21.0.2:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2017-04-03T19:55:20,747][INFO ][o.e.n.Node               ] [U95imVd] started
elasticsearch_1  | [2017-04-03T19:55:21,217][INFO ][o.e.g.GatewayService     ] [U95imVd] recovered [2] indices into cluster_state
elasticsearch_1  | [2017-04-03T19:55:21,923][INFO ][o.e.c.r.a.AllocationService] [U95imVd] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:22Z","tags":["status","plugin:elasticsearch@5.0.2","info"],"pid":11,"state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T19:55:22Z","tags":["status","ui settings","info"],"pid":11,"state":"green","message":"Status changed from red to green - Ready","prevState":"red","prevMsg":"Elasticsearch plugin is red"}
```

**Comment by elzii** [comment]
Here are some more logs:

### When running `node utils/import.js`

```
Elasticsearch ERROR: 2017-04-03T20:02:38Z
  Error: Request error, retrying
  POST http://localhost:9200/todo/todo/0 => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/Users/elzi/Development/tutorials/egghead-nodejs-api-swagger/todo-api/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/elzi/Development/tutorials/egghead-nodejs-api-swagger/todo-api/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/elzi/Development/tutorials/egghead-nodejs-api-swagger/todo-api/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/elzi/Development/tutorials/egghead-nodejs-api-swagger/todo-api/node_modules/lodash/lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)


Elasticsearch WARNING: 2017-04-03T20:04:08Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-04-03T20:04:08Z
  No living connections

```
These repeat for each JSON entry in `sample-todos.json`, truncated for clarity.


### When running `docker-compose up`

```
Starting eggheadnodejsapiswagger_elasticsearch_1
Creating eggheadnodejsapiswagger_kibana_1
Attaching to eggheadnodejsapiswagger_elasticsearch_1, eggheadnodejsapiswagger_kibana_1
eggheadnodejsapiswagger_elasticsearch_1 exited with code 137
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:25Z","tags":["status","plugin:kibana@5.3.0","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:25Z","tags":["status","plugin:elasticsearch@5.3.0","info"],"pid":11,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:25Z","tags":["status","plugin:console@5.3.0","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:26Z","tags":["status","plugin:timelion@5.3.0","info"],"pid":11,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:26Z","tags":["listening","info"],"pid":11,"message":"Server running at http://0.0.0.0:5601"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:26Z","tags":["status","ui settings","info"],"pid":11,"state":"yellow","message":"Status changed from uninitialized to yellow - Elasticsearch plugin is yellow","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:28Z","tags":["status","plugin:elasticsearch@5.3.0","error"],"pid":11,"state":"red","message":"Status changed from yellow to red - Request Timeout after 3000ms","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:02:28Z","tags":["status","ui settings","error"],"pid":11,"state":"red","message":"Status changed from yellow to red - Elasticsearch plugin is red","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow
```

Screenshot when visiting `http://localhost:5601`

![image](https://cloud.githubusercontent.com/assets/1827950/24629656/9f993d42-186e-11e7-876a-05002cb609d5.png)


### When running `localhost:9200/_cat/indices?v`

```
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

After some time, the docker logger starts outputting

```
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:10:36Z","tags":["error","elasticsearch","admin"],"pid":11,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:11:06Z","tags":["warning","elasticsearch","admin"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:11:11Z","tags":["warning","elasticsearch","admin"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:11:17Z","tags":["warning","elasticsearch","admin"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2017-04-03T20:11:22Z","tags":["warning","elasticsearch","admin"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```


## Observations

- No `elasticsearch_1` logs are seen in docker logs
- `ELASTICSEARCH_URL: "http://elasticsearch:9200"` <-- Why is this `elasticsearch` instead of `localhost` ?

**Comment by rekibnikufesin** [comment]
Line 4 in `docker-compose up`:
`eggheadnodejsapiswagger_elasticsearch_1 exited with code 137`
Docker tried to start the container but killed it because you're out of memory.

If your system is out of memory, try closing some programs to free up memory. If you aren't, try shutting down any running docker containers and restarting docker to see if that helps.

**Comment by rekibnikufesin** [comment]
Re: `ELASTICSEARCH_URL: "http://elasticsearch:9200" <-- Why is this elasticsearch instead of localhost ?`
It's the docker name that refers to the container defined [here](https://github.com/rekibnikufesin/nodejs-api-swagger/blob/master/docker-compose.yml#L3).
When built that way, communication between kibana and elasticsearch happens inside the docker hosts and not across your network. This allows you to have secure communication between containers without building your own security infrastructure to support it.

**Comment by elzii** [comment]
Awesome. Solved. Thanks so much for the help.

For future troubleshooters using MacOS with Docker for Mac:

- Go to Docker.app Preferences
- Advanced Tab
- Increase Memory via Slider and Apply & Restart


Screenshot:

![image](https://cloud.githubusercontent.com/assets/1827950/24633047/69043bbc-187b-11e7-92e2-eb0bc720dd17.png)

**Comment by rekibnikufesin** [comment]
Nice!
Thanks for the follow up!
